# Starter pipeline


# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: ls -al
  displayName: 'Run a one-line script'
- task: Snyk@2
  inputs:
    file: 'pom.xml'
    protect: false
    test: true
    #monitor: true
    authType: 'endpoint'
    endpoint: 'snyk'
    failBuild: false
    dev: false
    trustPolicies: false

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    options: 'clean install'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false

- task: Docker@2
  inputs:
    containerRegistry: 'deckerhub'
    repository: 'devopsaccelerator/devsec'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
